# Generated by Django 4.2 on 2025-01-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('P', 'Planta'), ('L', 'Lagartija'), ('T', 'Tierra'), ('A', 'Agua'), ('F', 'Fuego'), ('E', 'Eléctrico')], max_length=30),
        ),
    ]
