# Generated by Django 4.2 on 2025-01-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('P', 'Planta'), ('A', 'Agua'), ('F', 'Fuego'), ('L', 'Lagartija'), ('T', 'Tierra'), ('E', 'Eléctrico')], max_length=30),
        ),
    ]
